base_url: http://jruby-gradle.org/
local_tz: UTC
generation:
  :in_threads: 0
asciidoctor:
  :safe: unsafe
  :base_dir: null
  :attributes:
    compat-mode: '@'
    attribute-missing: warn
    relfileprefix: '../'
    outfilesuffix: '/'
    idprefix: ''
    idseparator: '-'
    icons: font
    sectanchors: ''
    linkattrs: ''
    source-highlighter: coderay
    prewrap: null
